### ISSUE TITLE
cmake file to find realsense2

### ISSUE THREAD

**Issue by guanming001** [UnaNancyOwen/RealSense2Sample#1]
Hi

Thanks for the wonderful code of organizing the sample programs for RealSense SDK 2.0

Is there any plan for adding the cmake file to find realsense2 similar to FindKinectSDK2.cmake in your Kinect2Sample program?

Currently I couldn't compile the sample code as realsense2 is not found but a short workaround is to refer to the CMakeLists.txt example in  https://github.com/zivsha/librealsense/tree/getting_started_example/examples/getting-started and

**Comment by UnaNancyOwen** [comment]
No, I don't have that plan.
librealsense provides realsense2Config.cmake. I think all developers should use it.
But, It is not contained in pre-built binaries that distributed on GitHub.
You need build librealsense from source code your self.

**Comment by guanming001** [comment]
Thanks for the advice, I am able to build the sample code successfully after building librealsense from source code.

Just one thing to note is that I will also need to manually copy realsense2.dll into the folder of the .exe in order to run the .exe

**Comment by UnaNancyOwen** [comment]
> Just one thing to note is that I will also need to manually copy realsense2.dll into the folder of the .exe in order to run the .exe

In general, It should add path to *.dll files directory to environment variable <code>PATH</code> when using library that built as dynamic link library.
In the case of librealsense on Windows, It is <code>C:\Program Files\librealsense2\bin</code> (or <code>C:\Program Files (x86)\librealsense2\bin</code>).
