### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by alidaf** [UnaNancyOwen/RealSense2Sample#3]
I can't compile any of the examples because I get undefined references, e.g.

> GNU-amd64-Linux/realsense.o: In function `RealSense::show()':
> realsense.cpp:(.text+0x20): undefined reference to `cv::String::allocate(unsigned int)'
> realsense.cpp:(.text+0x6c): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
> realsense.cpp:(.text+0x74): undefined reference to `cv::String::deallocate()'
> realsense.cpp:(.text+0x88): undefined reference to `cv::String::allocate(unsigned int)'
> realsense.cpp:(.text+0xc8): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
> realsense.cpp:(.text+0xd0): undefined reference to `cv::String::deallocate()'
> realsense.cpp:(.text+0xe0): undefined reference to `cv::String::deallocate()'
> realsense.cpp:(.text+0xec): undefined reference to `cv::String::deallocate()'
> GNU-amd64-Linux/realsense.o: In function `RealSense::update()':
> realsense.cpp:(.text+0x120): undefined reference to `rs2_pipeline_wait_for_frames'
> realsense.cpp:(.text+0x148): undefined reference to `rs2_frame_add_ref'

I've tried netbeans and eclipse and still get the same.

**Comment by UnaNancyOwen** [comment]
Probably, You are not linking dependent libraries properly.
Please install dependent libraries (RealSense SDK 2.0, OpenCV 3.x), and generate build file using CMake.

**Comment by alidaf** [comment]
Thanks, I managed to work it out. It just won't run - Couldn't resolve requests.

**Comment by alidaf** [comment]
I found out the reason for the error. The Raspberry Pi can only use the left camera for IR. Commenting out all of the right camera sections allows it to run. The only problem now is that nothing is actually rendered!
