### ISSUE TITLE
CMake error with realsense2Config.cmake

### ISSUE THREAD

**Issue by YangJiao1996** [UnaNancyOwen/RealSense2Sample#5]
Hi,

Thank you so much for the examples! I was trying to compile your code, but got some error messages in CMake:
```
CMake Error at C:/IntelCam/librealsense-2.18.0/build/realsense2Config.cmake:11 (message):
  File or directory C://include referenced by variable realsense2_INCLUDE_DIR
  does not exist !
Call Stack (most recent call first):
  C:/IntelCam/librealsense-2.18.0/build/realsense2Config.cmake:33 (set_and_check)
  CMakeLists.txt:18 (find_package)
```

The `realsense2Config.cmake` file under the `librealsenses` folder looks like this:
```
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()
```
Actually I know little about the syntax in `.cmake` files, I just wonder whether it could be an issue related to the `.cmake` file in librealsense?

**Comment by UnaNancyOwen** [comment]
You don't seem to be installing librealsense.
Why <code>realsense2Config.cmake</code> is under <code>/librealsense-2.18.0/build</code>?
Please build ans install librealsense from source code. (install by building <code>INSTALL</code> project.)

**Comment by YangJiao1996** [comment]
@UnaNancyOwen Thank you, it works perfectly now.
